import math
import os
import numpy.random as random
import torch
import torch.nn as nn
import torch.nn.functional as F

class LayerNormFirst(nn.Module):
    """ LayerNorm that supports two data formats: channels_last (default) or channels_first. 
    The ordering of the dimensions in the inputs. channels_last corresponds to inputs with 
    shape (batch_size, height, width, channels) while channels_first corresponds to inputs 
    with shape (batch_size, channels, height, width).
    """
    """
        Version of the LayerNorm layer but with the channels first

        Args:
            normalized_shape (int): size of the feature dimension
            eps (float): epsilon factor used in the LayerNorm equation. Default = 1e-6
    """
    def __init__(self, normalized_shape, eps=1e-6):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(normalized_shape))
        self.bias = nn.Parameter(torch.zeros(normalized_shape))
        self.eps = eps
        self.normalized_shape = (normalized_shape, )
    
    def forward(self, x):
        """
            Forward pass.

            Args:
                x (torch.tensor): input tensor

            Returns:
                output torch tensor
        """
        u = x.mean(1, keepdim=True)
        s = (x - u).pow(2).mean(1, keepdim=True)
        x = (x - u) / torch.sqrt(s + self.eps)
        x = self.weight[:, None, None] * x + self.bias[:, None, None]
        return x

class GRN(nn.Module):
    """ 
        GRN (Global Response Normalization) layer

        Args:
            dim (int): size in the feature dimension
    """
    def __init__(self, dim):
        super().__init__()
        self.gamma = nn.Parameter(torch.zeros(1, 1, 1, dim))
        self.beta = nn.Parameter(torch.zeros(1, 1, 1, dim))

    def forward(self, x):
        Gx = torch.norm(x, p=2, dim=(1,2), keepdim=True)
        Nx = Gx / (Gx.mean(dim=-1, keepdim=True) + 1e-6)
        return self.gamma * (x * Nx) + self.beta + x

def drop_path(x, drop_prob: float = 0., training: bool = False):
    """
        Drop path function - this is used in ConvNeXTV2 as an alternative to dropout. Modified
        for jittability from the original implementation

        Args:
            x (torch.tensor): the input tensor to the layer
            drop_prob (float): the probability to skip the layer
            training (bool): is in training mode or not
    """

    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor = torch.floor(random_tensor)
    random_tensor.div_(keep_prob)
    return x * random_tensor


class DropPath(nn.Module):
    """
        Drop paths layer

        Args:
            drop_prob (float): probability to skip the block
    """
    def __init__(self, drop_prob: float = 0.):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)

    def extra_repr(self):
        return f'drop_prob={round(self.drop_prob,3):0.3f}'

def _trunc_normal_(tensor, mean, std, a, b):
    """
        Truncated normal distribution for layer weight initialisation

        Args:
            tensor (torch.tensor): input tensor to initialise
            mean (float): mean of the distribution
            std (float): standard deviation of the distribution
            a (float): lower bound for truncation
            b (float): upper bound for truncation

        Returns:
            Initialised torch.tensor
    """

    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    # Values are generated by using a truncated uniform distribution and
    # then using the inverse CDF for the normal distribution.
    # Get upper and lower cdf values
    l = norm_cdf((a - mean) / std)
    u = norm_cdf((b - mean) / std)

    # Uniformly fill tensor with values from [l, u], then translate to
    # [2l-1, 2u-1].
    tensor.uniform_(2 * l - 1, 2 * u - 1)

    # Use inverse cdf transform for normal distribution to get truncated
    # standard normal
    tensor.erfinv_()

    # Transform to proper mean, std
    tensor.mul_(std * math.sqrt(2.))
    tensor.add_(mean)

    # Clamp to ensure it's in the proper range
    tensor.clamp_(min=a, max=b)
    return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    """
        Truncated normal distribution for layer weight initialisation

        Args:
            tensor (torch.tensor): input tensor to initialise
            mean (float): mean of the distribution
            std (float): standard deviation of the distribution
            a (float): lower bound for truncation
            b (float): upper bound for truncation

        Returns:
            Initialised torch.tensor
    """
    with torch.no_grad():
        return _trunc_normal_(tensor, mean, std, a, b)


class Block(nn.Module):
    """ ConvNeXtV2 Block.
    
        Args:
            dim (int): Number of input channels.
            drop_path (float): Drop path rate. Default = 0.
    """
    def __init__(self, dim, drop_path=0.):
        super().__init__()
        self.dwconv = nn.Conv2d(dim, dim, kernel_size=7, padding=3, groups=dim) # depthwise conv
        self.norm = nn.LayerNorm(dim, eps=1e-6)
        self.pwconv1 = nn.Linear(dim, 4 * dim) # pointwise/1x1 convs, implemented with linear layers
        self.act = nn.GELU()
        self.grn = GRN(4 * dim)
        self.pwconv2 = nn.Linear(4 * dim, dim)
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()

    def forward(self, x):
        """
            Forward pass.

            Args:
                x (torch.tensor): layer input

            Returns: layer output torch.tensor
        """
        input = x
        x = self.dwconv(x)
        x = x.permute(0, 2, 3, 1) # (N, C, H, W) -> (N, H, W, C)
        x = self.norm(x)
        x = self.pwconv1(x)
        x = self.act(x)
        x = self.grn(x)
        x = self.pwconv2(x)
        x = x.permute(0, 3, 1, 2) # (N, H, W, C) -> (N, C, H, W)

        x = input + self.drop_path(x)
        return x

class ConvNeXtV2WithVertexAndNuClass(nn.Module):
    """ ConvNeXtV2-based model
        
        Args:
            in_chans (int): Number of input image channels. Default = 1
            nu_classes (int): Number of neutrino classes. Default = 3
            trk_classes (int): Number of track counting classes. Default = 6
            shw_classes (int): Number of shower counting classes. Default = 6
            depths (tuple(int)): Number of blocks at each stage. Default: [3, 3, 9, 3]
            dims (tuple(int)): Feature dimension at each stage. Default: [96, 192, 384, 768]
            drop_path_rate (float): Drop path rate (skips a ConvNextV2 block). Default = 0.
            head_init_scale (float): Init scaling value for classifier weights and biases. Default: 1.
    """
    def __init__(self, in_chans=1, nu_classes=3, trk_classes=6, shw_classes=6, 
                 depths=[3, 3, 9, 3], dims=[96, 192, 384, 768], 
                 drop_path_rate=0., head_init_scale=1.
                 ):
        super().__init__()
        self.depths = depths
        self.full_blocks = nn.ModuleList() # stem and 3 intermediate downsampling conv layers
        stem = nn.Sequential(
            nn.Conv2d(in_chans, dims[0], kernel_size=4, stride=4),
            LayerNormFirst(dims[0], eps=1e-6) # Mod by Leigh for jit
        )

        dp_rates=[x.item() for x in torch.linspace(0, drop_path_rate, sum(depths))] 
        cur = 0
        for i in range(4):
            if i == 0:
                self.full_blocks.append(stem)
            else:
                downsample_layer = nn.Sequential(
                        LayerNormFirst(dims[i-1], eps=1e-6),
                        nn.Conv2d(dims[i-1], dims[i], kernel_size=2, stride=2),
                )
                self.full_blocks.append(downsample_layer)
                
            stage = nn.Sequential(
                *[Block(dim=dims[i], drop_path=dp_rates[cur + j]) for j in range(depths[i])]
            )
            self.full_blocks.append(stage)
            cur += depths[i]

        self.norm = nn.LayerNorm(dims[-1], eps=1e-6) # final norm layer
        self.nu_head  = nn.Linear(dims[-1]+2, nu_classes)  # +2 for the (drift, wire) vertex coords
        self.trk_head = nn.Linear(dims[-1]+2, trk_classes) # +2 for the (drift, wire) vertex coords
        self.shw_head = nn.Linear(dims[-1]+2, shw_classes) # +2 for the (drift, wire) vertex coords

        self.apply(self._init_weights)
        self.nu_head.weight.data.mul_(head_init_scale)
        self.nu_head.bias.data.mul_(head_init_scale)
        self.trk_head.weight.data.mul_(head_init_scale)
        self.trk_head.bias.data.mul_(head_init_scale)
        self.shw_head.weight.data.mul_(head_init_scale)
        self.shw_head.bias.data.mul_(head_init_scale)

    def _init_weights(self, m):
        """
            Initialise all Conv2d and Linear layers

            Args:
                m (nn.Module): the model to consider
        """
        if isinstance(m, (nn.Conv2d, nn.Linear)):
            trunc_normal_(m.weight, std=.02)
            nn.init.constant_(m.bias, 0)

    def forward_features(self, x):
        """ Perform the forward pass for each ConvNextv2 block. Modified compared to the
            official implementation to allow jittability

            Args:
                x: input to the layer

            Returns:
                Output from the layer
        """

        for full_block in self.full_blocks:
            x = full_block(x)
        return self.norm(x.mean([-2, -1])) # global average pooling, (N, C, H, W) -> (N, C)

    def forward(self, x, vtx):
        """ Forward pass

            Args:
                x: the input images to classify
                vtx: position of the reconstructed neutrino vertex in fractional coordinates

            Returns:
                The network predictions (without softmax)
        """

        x = self.forward_features(x)
        x = torch.cat((x, vtx), dim=1)
        nu = self.nu_head(x)
        n_trks = self.trk_head(x)
        n_shws = self.shw_head(x)
        return [nu, n_trks, n_shws]

